"""add password reset tokens

Revision ID: 837f378e1782
Revises: edbda0185676
Create Date: 2026-08-13 17:25:57.137061
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '837f378e1782'
down_revision: str | None = 'edbda0185676'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping the table is enough - MySQL removes its indexes and foreign keys
    # with it. The generated version dropped ix_..._user_id first, which InnoDB
    # refuses while the foreign key to users.id still needs it; because MySQL
    # DDL self-commits, the earlier drop would persist and leave the schema
    # inconsistent with alembic_version.
    op.drop_table('password_reset_tokens')
