"""add payments table

Revision ID: edbda0185676
Revises: 0001_initial
Create Date: 2026-08-12 20:21:42.891955
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'edbda0185676'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'ABANDONED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('authorization_url', sa.String(length=512), nullable=True),
    sa.Column('gateway_response', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_order_status', 'payments', ['order_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping the table is enough - MySQL removes its indexes and foreign
    # keys with it.
    #
    # The generated version dropped each index first and could not work:
    # InnoDB requires an index backing every foreign key, so
    # `DROP INDEX ix_payments_order_id` is refused while the FK to orders.id
    # still exists. Worse, DDL in MySQL self-commits, so the first drop
    # persisted before the second failed - leaving the table missing an index
    # while alembic_version still claimed this revision was applied.
    op.drop_table('payments')
